### ISSUE TITLE
[1.20.1, 1.20.4] v1.0.0 Requires Java 21

### ISSUE THREAD

**Issue by mr-yours-truly** [pnk2u/More-Fishing-Rod-Variants#2]
The default Java version for Minecraft 1.20.1 and 1.20.4 is Java 17, when the mod calls for use of Java 21. When loading the mod on either version with only it's own dependencies, the game crashes with the following error:
![Screenshot_mfrv](https://github.com/user-attachments/assets/86a685dc-c9ca-4cc7-aafd-822958497abf)
Tested on the Steam Deck OLED 512GB and Prism launcher v8.4 (Flatpak).

**Comment by pnk2u** [comment]
Thanks for reporting, this issue has been fixed in version 1.0.2. Please download the latest version 1.0.2.
